### ISSUE TITLE
Fat Static library

### ISSUE THREAD

**Issue by dimohamdy** [graphhopper/graphhopper-ios#5]
in https://github.com/graphhopper/graphhopper-ios#terminal

Are this generate fat static library that can use  for any device or simulator or not ?

**Comment by karussell** [comment]
Please use the mailing list to ask questions, only if there is a problem or bug post it on the issues.

**Comment by clns** [comment]
I'm gonna answer this here for the sake of completeness, indeed please use the mailing list for questions.

As the docs say:

> This method compiles the library for the following architectures: macosx, simulator, iphoneos, so using Xcode instead is recommended.

The Terminal method creates a giant file that holds all the architectures mentioned. This is usually not what you want, because Xcode will create the necessary architectures based on the target device(s) you're building for. So there isn't any reason why you would want to compile all the architectures in a giant file like that.

**Comment by dimohamdy** [comment]
i didn't want to make giant project size when   adding graphhopper-ios to my project (500 Mb) that make problem for my in pushing it to my git server

**Comment by clns** [comment]
You don't have to push to your git server the pre-built library or any graph data. That should be part of the build process once your repo is cloned to a dev machine. You can simply add graphhopper-ios as a submodule or subtree in your main git repo and link to the files accordingly.

**Comment by dimohamdy** [comment]
thanks  for fast replay 
depend on this link fat static lib will rejected from apple 
https://kodmunki.wordpress.com/2015/03/04/cocoa-touch-frameworks-for-ios8-remix/
 and explain how to bypass apple validation

**Comment by clns** [comment]
I don't know about this new policy, but graphhopper-ios currently works the "[j2objc](https://github.com/google/j2objc) way". I know about the new way of building iOS apps, using Frameworks instead of static libraries, but I just don't have enough information about it.
